# Generated by Django 6.0.2 on 2026-02-20 10:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city_id',
            field=models.CharField(blank=True, choices=[(10101, 'Visakhapatnam'), (10102, 'Vijayawada'), (10103, 'Guntur'), (10104, 'Nellore'), (10105, 'Kurnool'), (10106, 'Tirupati'), (10107, 'Kadapa'), (10108, 'Anantapur'), (10109, 'Ongole'), (10110, 'Eluru'), (10201, 'Itanagar'), (10202, 'Naharlagun'), (10203, 'Pasighat'), (10204, 'Ziro'), (10205, 'Tawang'), (10301, 'Guwahati'), (10302, 'Silchar'), (10303, 'Dibrugarh'), (10304, 'Jorhat'), (10305, 'Nagaon'), (10306, 'Tezpur'), (10307, 'Goalpara'), (10308, 'Bongaigaon'), (10309, 'Tinsukia'), (10310, 'Karimganj'), (10401, 'Patna'), (10402, 'Gaya'), (10403, 'Bhagalpur'), (10404, 'Muzaffarpur'), (10405, 'Purnia'), (10406, 'Darbhanga'), (10407, 'Bettiah'), (10408, 'Madhubani'), (10409, 'Ara'), (10410, 'Begusarai'), (10501, 'Raipur'), (10502, 'Bhilai'), (10503, 'Korba'), (10504, 'Bilaspur'), (10505, 'Durg'), (10506, 'Jagdalpur'), (10507, 'Ambikapur'), (10508, 'Raigarh'), (10601, 'Panaji'), (10602, 'Margao'), (10603, 'Vasco da Gama'), (10604, 'Mapusa'), (10605, 'Ponda'), (10701, 'Ahmedabad'), (10702, 'Surat'), (10703, 'Vadodara'), (10704, 'Rajkot'), (10705, 'Bhavnagar'), (10706, 'Jamnagar'), (10707, 'Gandhinagar'), (10708, 'Porbandar'), (10709, 'Anand'), (10710, 'Bhuj'), (10801, 'Faridabad'), (10802, 'Gurgaon'), (10803, 'Panipat'), (10804, 'Ambala'), (10805, 'Yamunanagar'), (10806, 'Karnal'), (10807, 'Rohtak'), (10808, 'Hisar'), (10901, 'Shimla'), (10902, 'Dharamshala'), (10903, 'Solan'), (10904, 'Mandi'), (10905, 'Bilaspur'), (10906, 'Kangra'), (11001, 'Ranchi'), (11002, 'Jamshedpur'), (11003, 'Dhanbad'), (11004, 'Bokaro'), (11005, 'Deoghar'), (11006, 'Hazaribagh'), (11007, 'Giridih'), (11008, 'Ramgarh'), (11101, 'Bengaluru'), (11102, 'Mysore'), (11103, 'Hubli'), (11104, 'Mangalore'), (11105, 'Belgaum'), (11106, 'Gulbarga'), (11107, 'Tumkur'), (11108, 'Davanagere'), (11109, 'Shivamogga'), (11110, 'Bellary'), (11201, 'Thiruvananthapuram'), (11202, 'Kochi'), (11203, 'Kozhikode'), (11204, 'Thrissur'), (11205, 'Kollam'), (11206, 'Palakkad'), (11207, 'Alappuzha'), (11208, 'Kannur'), (11301, 'Bhopal'), (11302, 'Indore'), (11303, 'Gwalior'), (11304, 'Jabalpur'), (11305, 'Ujjain'), (11306, 'Sagar'), (11307, 'Ratlam'), (11308, 'Satna'), (11309, 'Rewa'), (11310, 'Dewas'), (11401, 'Mumbai'), (11402, 'Pune'), (11403, 'Nagpur'), (11404, 'Thane'), (11405, 'Nashik'), (11406, 'Aurangabad'), (11407, 'Solapur'), (11408, 'Kolhapur'), (11409, 'Amravati'), (11410, 'Nanded'), (11411, 'Kalyan'), (11412, 'Akola'), (11501, 'Imphal'), (11502, 'Thoubal'), (11503, 'Bishnupur'), (11504, 'Churachandpur'), (11505, 'Senapati'), (11601, 'Shillong'), (11602, 'Tura'), (11603, 'Jowai'), (11604, 'Nongpoh'), (11605, 'Williamnagar'), (11701, 'Aizawl'), (11702, 'Lunglei'), (11703, 'Saiha'), (11704, 'Champhai'), (11705, 'Kolasib'), (11801, 'Kohima'), (11802, 'Dimapur'), (11803, 'Mokokchung'), (11804, 'Tuensang'), (11805, 'Wokha'), (11806, 'Zunheboto'), (11901, 'Bhubaneswar'), (11902, 'Cuttack'), (11903, 'Rourkela'), (11904, 'Berhampur'), (11905, 'Sambalpur'), (11906, 'Puri'), (11907, 'Balasore'), (11908, 'Baripada'), (11909, 'Koraput'), (11910, 'Sundargarh'), (12001, 'Ludhiana'), (12002, 'Amritsar'), (12003, 'Jalandhar'), (12004, 'Patiala'), (12005, 'Bathinda'), (12006, 'Mohali'), (12007, 'Hoshiarpur'), (12008, 'Firozpur'), (12101, 'Jaipur'), (12102, 'Jodhpur'), (12103, 'Kota'), (12104, 'Bikaner'), (12105, 'Udaipur'), (12106, 'Ajmer'), (12107, 'Alwar'), (12108, 'Sikar'), (12109, 'Sawai Madhopur'), (12110, 'Bharatpur'), (12201, 'Gangtok'), (12202, 'Namchi'), (12203, 'Gyalshing'), (12301, 'Chennai'), (12302, 'Coimbatore'), (12303, 'Madurai'), (12304, 'Tiruchirappalli'), (12305, 'Salem'), (12306, 'Tirunelveli'), (12307, 'Erode'), (12308, 'Vellore'), (12309, 'Thoothukudi'), (12310, 'Nagercoil'), (12401, 'Hyderabad'), (12402, 'Warangal'), (12403, 'Nizamabad'), (12404, 'Karimnagar'), (12405, 'Khammam'), (12406, 'Mahbubnagar'), (12407, 'Siddipet'), (12408, 'Bhongir'), (12501, 'Agartala'), (12502, 'Dharmanagar'), (12503, 'Udaipur'), (12504, 'Kailasahar'), (12505, 'Ambassa'), (12601, 'Lucknow'), (12602, 'Kanpur'), (12603, 'Ghaziabad'), (12604, 'Agra'), (12605, 'Meerut'), (12606, 'Varanasi'), (12607, 'Prayagraj'), (12608, 'Bareilly'), (12609, 'Aligarh'), (12610, 'Moradabad'), (12611, 'Saharanpur'), (12612, 'Gorakhpur'), (12701, 'Dehradun'), (12702, 'Haridwar'), (12703, 'Roorkee'), (12704, 'Haldwani'), (12705, 'Pantnagar'), (12706, 'Rishikesh'), (12801, 'Kolkata'), (12802, 'Howrah'), (12803, 'Durgapur'), (12804, 'Asansol'), (12805, 'Siliguri'), (12806, 'Malda'), (12807, 'Kharagpur'), (12808, 'Bardhaman'), (12809, 'Berhampore'), (12810, 'Raiganj'), (12901, 'New Delhi'), (12902, 'Old Delhi'), (12903, 'Delhi Cantonment'), (12904, 'Rohini'), (12905, 'Dwarka'), (13001, 'Port Blair'), (13002, 'Diglipur'), (13003, 'Mayabunder'), (13004, 'Nancowry'), (13101, 'Chandigarh'), (13201, 'Daman'), (13202, 'Diu'), (13203, 'Silvassa'), (13204, 'Karanja'), (13205, 'Vapi'), (13301, 'Srinagar'), (13302, 'Jammu'), (13303, 'Anantnag'), (13304, 'Baramulla'), (13305, 'Pulwama'), (13306, 'Kathua'), (13307, 'Udhampur'), (13308, 'Kulgam'), (13401, 'Leh'), (13402, 'Kargil'), (13403, 'Nubra'), (13404, 'Drass'), (13501, 'Kavaratti'), (13502, 'Agatti'), (13503, 'Kadmat'), (13601, 'Puducherry'), (13602, 'Karaikal'), (13603, 'Mahe'), (13604, 'Yanam'), (13605, 'Villianur'), (13606, 'Ozhukarai'), (20101, 'Toronto'), (20102, 'Ottawa'), (20103, 'Mississauga'), (20104, 'BRAMPTON'), (20201, 'Vancouver'), (20202, 'Victoria'), (20203, 'Surrey'), (20301, 'Montreal'), (20302, 'Quebec City'), (20303, 'Laval'), (20401, 'Calgary'), (20402, 'Edmonton'), (20403, 'Red Deer'), (20501, 'Winnipeg'), (20502, 'Brandon'), (20601, 'Halifax'), (20602, 'Sydney'), (40101, 'Sydney'), (40102, 'Newcastle'), (40103, 'Wollongong'), (40201, 'Melbourne'), (40202, 'Geelong'), (40203, 'Ballarat'), (40301, 'Brisbane'), (40302, 'Gold Coast'), (40303, 'Cairns'), (40401, 'Perth'), (40402, 'Fremantle'), (40403, 'Bunbury'), (40501, 'Adelaide'), (40502, 'Mount Gambier'), (40503, 'Whyalla'), (40601, 'Hobart'), (40602, 'Launceston'), (40603, 'Devonport'), (40701, 'Canberra'), (40801, 'Darwin'), (40802, 'Alice Springs'), (40803, 'Katherine')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_id',
            field=models.CharField(blank=True, choices=[(1, 'India'), (2, 'Canada'), (4, 'Australia')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_of_birth_id',
            field=models.CharField(blank=True, choices=[(1, 'India'), (2, 'Canada'), (4, 'Australia')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_of_citizenship_id',
            field=models.CharField(blank=True, choices=[(1, 'India'), (2, 'Canada'), (4, 'Australia')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='file_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('Other', 'Other')], default='English', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_Indigenous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mailing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parents_attend_uni_or_college',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previous_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state_id',
            field=models.CharField(blank=True, choices=[(101, 'Andhra Pradesh'), (102, 'Arunachal Pradesh'), (103, 'Assam'), (104, 'Bihar'), (105, 'Chhattisgarh'), (106, 'Goa'), (107, 'Gujarat'), (108, 'Haryana'), (109, 'Himachal Pradesh'), (110, 'Jharkhand'), (111, 'Karnataka'), (112, 'Kerala'), (113, 'Madhya Pradesh'), (114, 'Maharashtra'), (115, 'Manipur'), (116, 'Meghalaya'), (117, 'Mizoram'), (118, 'Nagaland'), (119, 'Odisha'), (120, 'Punjab'), (121, 'Rajasthan'), (122, 'Sikkim'), (123, 'Tamil Nadu'), (124, 'Telangana'), (125, 'Tripura'), (126, 'Uttar Pradesh'), (127, 'Uttarakhand'), (128, 'West Bengal'), (129, 'Delhi (NCT)'), (130, 'Andaman and Nicobar Islands'), (131, 'Chandigarh'), (132, 'Dadra and Nagar Haveli and Daman and Diu'), (133, 'Jammu and Kashmir'), (134, 'Ladakh'), (135, 'Lakshadweep'), (136, 'Puducherry'), (201, 'Ontario'), (202, 'British Columbia'), (203, 'Quebec'), (204, 'Alberta'), (205, 'Manitoba'), (206, 'Nova Scotia'), (401, 'New South Wales'), (402, 'Victoria'), (403, 'Queensland'), (404, 'Western Australia'), (405, 'South Australia'), (406, 'Tasmania'), (407, 'Australian Capital Territory'), (408, 'Northern Territory')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
