# Generated by Django 6.0.2 on 2026-02-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_userprofile_contact_no_userprofile_city_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('Chinese', 'Chinese'), ('Other', 'Other')], default='English', max_length=20, null=True),
        ),
    ]
